### ISSUE TITLE
Can we call Go From C++ using SWIG

### ISSUE THREAD

**Issue by DinoStray** [draffensperger/go-interlang#3]
I know we can call C++ from Go using SWIG.
But can we call Go From C++ using SWIG?

**Comment by draffensperger** [comment]
So for calling Go from C++, I don't think you need SWIG because Go's functions follow normal C calling conventions, which C++ can also use, see this example here: https://github.com/draffensperger/go-interlang/blob/8f58ebad52359723ffddfa626ddc847a96b5543a/c_to_go/cxx_to_go_dyn_lib/main.cxx#L8

What would be your motivation for using SWIG for calling from C++ to Go?
